name: README to PDF
on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build README PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./README.md
          table_of_contents: true
          output_dir: pdf
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          path: pdf/README.pdf